package com.astroeleven.app.utils

object Localization {
    // English Strings
    // English Strings
    private val english = mapOf(
        "home_title" to "Astro Eleven",
        "home" to "Home",
        "profile" to "Profile",
        "settings" to "Settings",
        "logout" to "Logout",
        "join_as_astrologer" to "Join as Astrologer",
        "name" to "Full Name",
        "phone_number" to "Phone Number",
        "email_address" to "Email Address",
        "experience_years" to "Experience (Years)",
        "skills_expert" to "Skills (e.g. Vedic, Tarot)",
        "price_per_min" to "Price Per Min",
        "about_you" to "About You",
        "register_now" to "Register Now",
        "premium_consultation" to "Premium Consultation",
        "vedic_remedies" to "Vedic Remedies",
        "gemstone_guide" to "Gemstone Guide",
        "horoscope" to "Horoscope",
        "daily_horoscope" to "Daily Horoscope",
        "chat_services" to "Chat Services",
        "video_call" to "Video Call",
        "audio_call" to "Audio Call",
        "view_all" to "View All",
        "loading" to "Loading...",
        "aries" to "Aries",
        "taurus" to "Taurus",
        "gemini" to "Gemini",
        "cancer" to "Cancer",
        "leo" to "Leo",
        "virgo" to "Virgo",
        "libra" to "Libra",
        "scorpio" to "Scorpio",
        "sagittarius" to "Sagittarius",
        "capricorn" to "Capricorn",
        "aquarius" to "Aquarius",
        "pisces" to "Pisces",
        "all" to "All",
        "love" to "Love",
        "career" to "Career",
        "finance" to "Finance",
        "marriage" to "Marriage",
        "health" to "Health",
        "education" to "Education",
        "element" to "Element",
        "lord" to "Lord",
        "category" to "Category",
        "daily_prediction" to "Daily Prediction",
        "ok" to "OK",
        "personal_details" to "Personal Details",
        "partner_details" to "Partner Details",
        "dob" to "Date of Birth",
        "tob" to "Time of Birth",
        "pob" to "Place of Birth",
        "gender" to "Gender",
        "male" to "Male",
        "female" to "Female",
        "occupation" to "Occupation",
        "marital_status" to "Marital Status",
        "topic" to "Problem Topic",
        "submit_consultation" to "Start Consultation",
        "unknown_time" to "I don't know my birth time",
        "select_city" to "Select City",
        "full_name" to "Full Name",
        "single" to "Single",
        "married" to "Married",
        "divorced" to "Divorced",
        "widowed" to "Widowed",
        "career_/_job" to "Career / Job",
        "marriage_/_relationship" to "Marriage / Relationship",
        "health" to "Health",
        "finance" to "Finance",
        "legal" to "Legal",
        "general" to "General",
        "basic_info" to "Basic Information",
        "birth_details" to "Birth Details",
        "contact_details" to "Contact Information",
        "professional_details" to "Professional Details",
        "payment_details" to "Payment Details",
        "real_name" to "Real Name (as per Aadhar)",
        "display_name" to "Display Name",
        "whatsapp_number" to "WhatsApp Number",
        "full_address" to "Full Address",
        "aadhar_number" to "Aadhar Number",
        "pan_number" to "PAN Number",
        "bank_details" to "Bank Details (A/C, IFSC)",
        "upi_id" to "UPI ID / Name",
        "please_fill_required" to "Please fill required fields (*)",
        "home_welcome" to "Welcome, %s",
        "wallet_balance" to "Wallet Balance",
        "add_money" to "Add Money",
        "quick_actions" to "Quick Services",
        "chat" to "Chat",
        "call" to "Call",
        "video_call_mini" to "Video Call",
        "featured_guide" to "Featured Guide",
        "zodiac_insights" to "Zodiac Insights",
        "daily_rituals" to "Daily Rituals",
        "policies_support" to "Policies & Support",
        "customer_stories" to "Customer Stories",
        "talk_now" to "Talk Now",
        "chat_now" to "Chat Now",
        "low_balance" to "Low Balance!",
        "low_balance_msg" to "Insufficient funds. Please recharge.",
        "recharge_now" to "Recharge Now",
        "later" to "Later",
        "expand_chart" to "Expand Chart",
        "show_less" to "Show Less",
        "featured_guide_desc" to "View All",
        "online" to "ONLINE",
        "orders" to "Orders",
        "years" to "Years",
        "exp" to "Exp:",
        "copy" to "COPY",
        "whatsapp_share" to "Share on WhatsApp",
        "referral_code" to "Referral Code",
        "referral" to "Referral",
        "claim" to "Claim",
        "refer_win" to "🎁 Refer & Win!",
        "refer_desc" to "Invite friends and earn rewards",
        "connecting_title" to "Connecting to Astrologer...",
        "connecting_subtitle" to "Please stay on this screen while we establish a secure connection",
        "cancel_request" to "Cancel Request",
        "mahadasha" to "Maha Dasha",
        "bhukti" to "Bhukti",
        "antharam" to "Antharam",
        "pratyantharam" to "Pratyantharam",
        "sookshma" to "Sookshma",
        "remedies" to "Remedies",
        "video" to "Video",
        "top_rated" to "Top Rated",
        "must_try" to "Must Try",
        "elite" to "Elite",
        "min" to "min"
    )

    // Tamil Strings
    private val tamil = mapOf(
        "home_title" to "Astro Eleven",
        "home" to "முகப்பு",
        "profile" to "சுயவிவரம்",
        "settings" to "அமைப்புகள்",
        "logout" to "வெளியேறு",
        "join_as_astrologer" to "ஜோதிடராக இணையுங்கள்",
        "name" to "முழு பெயர்",
        "phone_number" to "தொலைபேசி எண்",
        "email_address" to "மின்னஞ்சல் முகவரி",
        "experience_years" to "அனுபவம் (ஆண்டுகள்)",
        "skills_expert" to "திறன்கள் (உதாரணம்: வேத, டாரோட்)",
        "price_per_min" to "நிமிடத்திற்கு கட்டணம்",
        "about_you" to "உங்களைப் பற்றி",
        "register_now" to "பதிவு செய்க",
        "premium_consultation" to "பிரீமியம் ஆலோசனை",
        "vedic_remedies" to "வேத பரிகாரங்கள்",
        "gemstone_guide" to "ரத்தின வழிகாட்டி",
        "horoscope" to "ராசி பலன்",
        "daily_horoscope" to "தினசரி ராசி பலன்",
        "chat_services" to "சாட் சேவை",
        "video_call" to "வீடியோ அழைப்பு",
        "audio_call" to "ஆடியோ அழைப்பு",
        "view_all" to "அனைத்தையும் பார்க்க",
        "loading" to "ஏற்றுகிறது...",
        "aries" to "மேஷம்",
        "taurus" to "ரிஷபம்",
        "gemini" to "மிதுனம்",
        "cancer" to "கடகம்",
        "leo" to "சிம்மம்",
        "virgo" to "கன்னி",
        "libra" to "துலாம்",
        "scorpio" to "விருச்சிகம்",
        "sagittarius" to "தனுசு",
        "capricorn" to "மகரம்",
        "aquarius" to "கும்பம்",
        "pisces" to "மீனம்",
        "all" to "அனைத்தும்",
        "love" to "காதல்",
        "career" to "வேலைவாய்ப்பு",
        "finance" to "நிதி",
        "marriage" to "திருமணம்",
        "health" to "உடல்நலம்",
        "education" to "கல்வி",
        "element" to "தத்துவம்",
        "lord" to "அதிபதி",
        "category" to "வகை",
        "daily_prediction" to "இன்றைய பலன்",
        "ok" to "OK",
        "personal_details" to "தனிப்பட்ட விவரங்கள்",
        "partner_details" to "துணைவர் விவரங்கள்",
        "dob" to "பிறந்த தேதி",
        "tob" to "பிறந்த நேரம்",
        "pob" to "பிறந்த இடம்",
        "gender" to "பாலினம்",
        "male" to "ஆண்",
        "female" to "பெண்",
        "occupation" to "தொழில்",
        "marital_status" to "திருமண நிலை",
        "topic" to "கேள்வித் தலைப்பு",
        "submit_consultation" to "ஆலோசனையைத் தொடங்கவும்",
        "unknown_time" to "பிறந்த நேரம் தெரியவில்லை",
        "select_city" to "நகரத்தைத் தேர்ந்தெடுக்கவும்",
        "full_name" to "முழு பெயர்",
        "single" to "திருமணமாகாதவர்",
        "married" to "திருமணமானவர்",
        "divorced" to "விவாகரத்தானவர்",
        "widowed" to "துணையை இழந்தவர்",
        "career_/_job" to "வேலை / தொழில்",
        "marriage_/_relationship" to "திருமணம் / உறவு",
        "health" to "உடல்நலம்",
        "finance" to "நிதி",
        "legal" to "சட்டம்",
        "general" to "பொதுவானது",
        "basic_info" to "அடிப்படை விவரங்கள்",
        "birth_details" to "பிறப்பு விவரங்கள்",
        "contact_details" to "தொடர்பு விவரங்கள்",
        "professional_details" to "தொழில்முறை விவரங்கள்",
        "payment_details" to "கட்டண விவரங்கள்",
        "real_name" to "உண்மையான பெயர் (ஆதார் படி)",
        "display_name" to "காட்சி பெயர்",
        "whatsapp_number" to "வாட்ஸ்அப் எண்",
        "full_address" to "முழு முகவரி",
        "aadhar_number" to "ஆதார் எண்",
        "pan_number" to "பான் எண்",
        "bank_details" to "வங்கி விவரங்கள் (A/C, IFSC)",
        "upi_id" to "UPI விவரம்",
        "please_fill_required" to "சிவப்பு நட்சத்திரம் (*) உள்ள கட்டாய புலங்களை நிரப்பவும்",
        "home_welcome" to "வரவேற்கிறோம், %s",
        "wallet_balance" to "வாலட் இருப்பு",
        "add_money" to "பணம் சேர்க்க",
        "quick_actions" to "விரைவும் சேவைகள்",
        "chat" to "சாட்",
        "call" to "அழைப்பு",
        "video_call_mini" to "வீடியோ",
        "featured_guide" to "சிறப்பு வழிகாட்டி",
        "zodiac_insights" to "ராசி பலன்கள்",
        "daily_rituals" to "தினசரி வழிபாடுகள்",
        "policies_support" to "Policies & Support",
        "customer_stories" to "வாடிக்கையாளர் கதைகள்",
        "talk_now" to "ஆலோசனை",
        "chat_now" to "சாட் செய்தி",
        "low_balance" to "குறைந்த இருப்பு!",
        "low_balance_msg" to "போதிய பணம் இல்லை. தயவுசெய்து ரீசார்ஜ் செய்யவும்.",
        "recharge_now" to "ரீசார்ஜ் செய்க",
        "later" to "பிறகு",
        "expand_chart" to "விரிவாக்கம்",
        "show_less" to "சுருக்குக",
        "featured_guide_desc" to "அனைத்தையும் பார்க்க",
        "online" to "ஆன்லைனில்",
        "orders" to "ஆர்டர்கள்",
        "years" to "ஆண்டுகள்",
        "exp" to "அனுபவம்:",
        "copy" to "நகல் எடு",
        "whatsapp_share" to "வாட்ஸ்அப்பில் பகிரவும்",
        "referral_code" to "Referral Code",
        "referral" to "பரிந்துரை",
        "claim" to "Claim",
        "refer_win" to "🎁 பரிசு வெல்லுங்கள்!",
        "refer_desc" to "நண்பர்களை அழைத்து வாலட் பணத்தை அள்ளுங்கள்",
        "connecting_title" to "ஜோதிடருடன் இணைகிறது...",
        "connecting_subtitle" to "இணைப்பு உறுதி செய்யப்படும் வரை தயவுசெய்து காத்திருக்கவும்",
        "cancel_request" to "ரத்து செய்",
        "mahadasha" to "மகா தசை",
        "bhukti" to "புத்தி",
        "antharam" to "அந்தரம்",
        "pratyantharam" to "பிரத்யந்தரம்",
        "sookshma" to "சூட்சமம்",
        "remedies" to "பரிகாரங்கள்",
        "video" to "வீடியோ",
        "top_rated" to "மிகவும் சிறந்தவர்",
        "must_try" to "முயற்சிக்க வேண்டியவர்",
        "elite" to "எலைட்",
        "min" to "நிமிடம்"
    )


    fun get(key: String, isTamil: Boolean): String {
        return if (isTamil) {
            tamil[key] ?: english[key] ?: key
        } else {
            english[key] ?: key
        }
    }
}

